# Generated by Django 5.2.7 on 2025-10-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujong', models.CharField(max_length=100, verbose_name='수종')),
                ('gwa', models.CharField(max_length=100, verbose_name='과')),
                ('leaf_shape_overall', models.CharField(blank=True, max_length=50, verbose_name='전체적 잎 모양')),
                ('form', models.CharField(blank=True, max_length=100, verbose_name='형태')),
                ('leaf_shape_detail', models.CharField(blank=True, max_length=100, verbose_name='잎이 생긴 모양')),
                ('leaf_length', models.CharField(blank=True, max_length=50, verbose_name='잎 길이(mm/cm)')),
                ('leaf_arrangement', models.CharField(blank=True, max_length=50, verbose_name='잎이 나는 모양')),
                ('leaf_margin', models.CharField(blank=True, max_length=50, verbose_name='잎가장자리')),
                ('leaf_margin_detail', models.CharField(blank=True, max_length=100, verbose_name='잎가장자리 생김새')),
                ('sting_feel', models.CharField(blank=True, max_length=100, verbose_name='잎에 찔렸을 때')),
                ('special_notes', models.TextField(blank=True, verbose_name='특이사항')),
                ('leaf_tip', models.CharField(blank=True, max_length=100, verbose_name='잎끝')),
                ('petiole', models.CharField(blank=True, max_length=100, verbose_name='잎자루')),
                ('vein', models.CharField(blank=True, max_length=100, verbose_name='잎맥')),
                ('height', models.CharField(blank=True, max_length=50, verbose_name='키')),
                ('fruit_flower', models.TextField(blank=True, verbose_name='열매,꽃')),
            ],
        ),
    ]
